spring:
  datasource:
    url: jdbc:mysql://${MYSQL_IP}:${MYSQL_PORT}/sakila?serverTimezone=UTC
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
